#локальна/проєктна кастомізація: змінні середовища, додаткові сервіси, volume'и, вимоги тощо.

version: '3.8'

services:
  airflow:
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
    volumes:
      - ./dags:/opt/airflow/dags
      - ./ocr:/opt/airflow/ocr
      - ./enrichment:/opt/airflow/enrichment
      - ./db:/opt/airflow/db
      - ./marketing_materials:/opt/airflow/marketing_materials
      - ./requirements.txt:/requirements.txt
    command: >
      bash -c "
        airflow db init &&
        airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin &&
        airflow webserver"

  marketing_db:
    image: postgres:13
    container_name: marketing_db
    environment:
      POSTGRES_USER: marketing
      POSTGRES_PASSWORD: marketing
      POSTGRES_DB: marketing_data
    ports:
      - "5433:5432"
    volumes:
      - marketing_pgdata:/var/lib/postgresql/data

volumes:
  marketing_pgdata:
